export const badgeMap = {
  React: 'https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB',
  'React Router': 'https://img.shields.io/badge/React_Router-CA4245?style=for-the-badge&logo=reactrouter&logoColor=white',
  Vite: 'https://img.shields.io/badge/Vite-646CFF?style=for-the-badge&logo=vite&logoColor=white',
  SCSS: 'https://img.shields.io/badge/SCSS-cc6699?style=for-the-badge&logo=sass&logoColor=white',
  // 'SCSS Modules': 'https://img.shields.io/badge/SCSS-cc6699?style=for-the-badge&logo=sass&logoColor=white',
  'Node.js': 'https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=node.js&logoColor=white',
  Express: 'https://img.shields.io/badge/Express-000000?style=for-the-badge&logo=express&logoColor=white',
  // 'Express.js': 'https://img.shields.io/badge/Express-000000?style=for-the-badge&logo=express&logoColor=white',
  PostgreSQL: 'https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white',
  JWT: 'https://img.shields.io/badge/JWT-000000?style=for-the-badge&logo=jsonwebtokens&logoColor=white',
  Stripe: 'https://img.shields.io/badge/Stripe-635BFF?style=for-the-badge&logo=stripe&logoColor=white',
  Jest: 'https://img.shields.io/badge/Jest-C21325?style=for-the-badge&logo=jest&logoColor=white',
  'React Testing Library': 'https://img.shields.io/badge/React_Testing_Library-E33332?style=for-the-badge&logo=testinglibrary&logoColor=white',
  Supertest: 'https://img.shields.io/badge/Supertest-000000?style=for-the-badge&logo=supertest&logoColor=white',
  'Next.js': 'https://img.shields.io/badge/Next.js-000?style=for-the-badge&logo=next.js&logoColor=white',
  // 'Next.js 14': 'https://img.shields.io/badge/Next.js_14-000?style=for-the-badge&logo=next.js&logoColor=white',
  'Context API': 'https://img.shields.io/badge/Context_API-61DAFB?style=for-the-badge',
  Prisma: 'https://img.shields.io/badge/Prisma-2D3748?style=for-the-badge&logo=prisma&logoColor=white',
  Supabase: 'https://img.shields.io/badge/Supabase-3ECF8E?style=for-the-badge&logo=supabase&logoColor=white',
  // 'Supabase Storage': 'https://img.shields.io/badge/Supabase_Storage-3ECF8E?style=for-the-badge&logo=supabase&logoColor=white',
  bcrypt: 'https://img.shields.io/badge/bcrypt-0d1117?style=for-the-badge',
  Axios: 'https://img.shields.io/badge/Axios-5A29E4?style=for-the-badge&logo=axios&logoColor=white',
  Vercel: 'https://img.shields.io/badge/Vercel-000?style=for-the-badge&logo=vercel&logoColor=white',
  'AWS EC2': 'https://img.shields.io/badge/AWS_EC2-FF9900?style=for-the-badge&logo=amazonaws&logoColor=white',
  'Railway': 'https://img.shields.io/badge/Railway-000000?style=for-the-badge&logo=railway&logoColor=white',
  'Tone.js': 'https://img.shields.io/badge/Tone.js-ff7373?style=for-the-badge',
  'Drei': 'https://img.shields.io/badge/@react-three/drei-000000?style=for-the-badge&logo=three.js&logoColor=white',
'React Three Fiber': 'https://img.shields.io/badge/React_Three_Fiber-000000?style=for-the-badge&logo=three.js&logoColor=white',
'Three.js': 'https://img.shields.io/badge/Three.js-000000?style=for-the-badge&logo=three.js&logoColor=white',

  'Figma': 'https://img.shields.io/badge/Figma-F24E1E?style=for-the-badge',
  
  // Added music and 3D tools:
  Ableton: 'https://img.shields.io/badge/Ableton_Live-000000?style=for-the-badge&logo=abletonlive&logoColor=white',
  'Pro Tools': 'https://img.shields.io/badge/Pro_Tools-6E2B96?style=for-the-badge&logo=protools&logoColor=white',
  Avid: 'https://img.shields.io/badge/Avid-1E1E1E?style=for-the-badge&logo=avid&logoColor=white',
  Blender: 'https://img.shields.io/badge/Blender-F5792A?style=for-the-badge&logo=blender&logoColor=white',
};
